name: 📰 Auto Update International News

on:
  schedule:
    - cron: '*/22 * * * *'  # 每 22 分钟执行一次
#    - cron: '0 */2 * * *'  # 每 2 小时的整点执行一次
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: ✅ Checkout Code
        uses: actions/checkout@v3

      - name: 🔧 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install Dependencies
        run: pip install feedparser

      - name: ⏱️ Random Delay (0~2 min)
        run: |
          delay=$(( RANDOM % 50 ))
          echo "⏳ Random delay: $delay seconds..."
          sleep $delay

      - name: 📰 Run News Fetcher
        run: python fetch_news.py

      - name: 📂 Commit & Push Changes
        run: |
          git config --global user.name "bossvpn"
          git config --global user.email "206999043+chatgpt-helper-tech@users.noreply.github.com"

          git add .
          if git diff --cached --quiet; then
            echo "✅ No changes to commit."
          else
            RAND=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 6)
            git commit -m "📰 auto: update news at $(date -u '+%Y-%m-%d %H:%M:%S') UTC | $RAND"
            git pull --rebase --autostash
            git push origin HEAD:${{ github.ref_name }}
          fi
